### ISSUE TITLE
Tietueen tuominen TäTistä Vaaraan ei tuo oikeaa tallennuspohjaa

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/koha-plugin-auto-framework-code#1]
### Mikä vikana?

Vaikka TäTissä on nimeketietueella oikea tallennuspohja (kirja), se ei tule Vaaraan kirjapohjana vaan muuttuu oletuspohjaksi. Tämä ongelma on ollut jo Kohan viime versiosta lähtien (ja jatkuu nykyisessä versiossa), vaikka aikaisemmin kuvailupohja pysyi oikeana.

**Comment by AnneliO** [comment]
Tähän liittynee tämä Redminen tiketti: https://tiketti.koha-suomi.fi/issues/4583

Tuo odottaa edelleen edelliseen/nykyiseen versioon tuontia.

**Comment by emta001** [comment]
> Tähän liittynee tämä Redminen tiketti: https://tiketti.koha-suomi.fi/issues/4583
> 
> Tuo odottaa edelleen edelliseen/nykyiseen versioon tuontia.

Ohops, miten tuo on päässyt livahtamaan noin pahasti? :O Voitaisiin ottaa tämä palsussa esille ja vastuuttaa jollekulle, niin saadaan asetus nyt viimein matkaan mukaan.

**Comment by paxed** [comment]
Tämä on nyt vaaran testillä.

Konfiguraatio hoituu "Auto Framework Code" - pluginin avulla, jonne laitetaan sama YAML-rimpsu kuin mitä oli aikaisemmin tuossa MarcToFrameworkcodeAutoconvert-järjestelmäasetuksessa

**Comment by pirliis** [comment]
Saisiko tämän myös OUTIn testille? Mistähän saisimme vanhat asetussäädöt?

**Comment by pirliis** [comment]
> Saisiko tämän myös OUTIn testille? Mistähän saisimme vanhat asetussäädöt?

Antilta löytyi asetussäädöt. :)

**Comment by paxed** [comment]
On nyt myös outi-testillä

**Comment by AnneliO** [comment]
Tässä on OUTIn asetukset Auto Framwork Code -liitännäisen määrittelyyn:

```
---
- 000/06 + 000/07:
   a+s: SER
- 000/06:
   a: KIR
   c: NUO
   e: MAP
   g: VR
   j: CDA
   r: LAU
   t: KIR
- 008/26 + 000/06:
   g+m: KP
```

Hoksautatko Pasi, kun olet lisännyt liitännäisen kaikkien kimppojen testeille, niin pääkäyttäjät voisivat käydä sitten lisäämässä nuo itselleen? :)

**Comment by AnttHeik** [comment]
@AnneliO Onko tuo OUTIn asetusten asettelu just samalla tavalla muotoiltu kuin ne oli aiemmassa Kohan versiossa? Silloin niiden muotoilussa oli jotain häikkää aluksi, minkä takia toiminto toimi ehkä vähän eri tavalla kuin sen jälkeen kun asettelu oli korjattu.

OUTIn testillä liitännäinen toimii nyt näin:

Perustiedot-näyttö:
- Oletuspohjalla olevan tietueen päälle vaihtuu heti esim. kirjapohja, kun tietue tuodaan Z39.50/SRU-haulla.
- Aina kun tietueen tallentaa, pohja vaihtuu ns. väkisin, vaikka yrität tallentaa kirjatietueen oletuspohjalla, niin pohja vaihtuu kirjapohjaksi. (Tämä tuli nyt uutena asiana. Mielestäni tätä ei tapahtunut aiemmin. En oikein tiedä, onko tämä hyvä vai huono juttu.)

Kuvailu-osio:
- Kun tietue poimitaan Z39.50/SRU-haulla, tietue avautuu näytölle oletuspohjalla eikä vaihdu suoraan esim. kirjapohjaksi (Tässä osiossa on kyllä toisaalta mahdollista hakea tietuetta myös suoraan jollakin pohjavalinnalla)
- Pohja vaihtuu oikeaksi pohjaksi (esim. oletuspohja kirjapohjaksi) tallennuksen yhteydessä.

Mutta periaatteessa tämä toimii minusta nyt ihan hyvin kuitenkin ainakin OUTIn testillä, koska tärkeintä on että pohja vaihtuu oikein kun tietueita tuodaan valutuksen kautta tai hankintaportaalista. Mitenköhän Vaarassa tai muilla kimpoilla?

**Comment by AnneliO** [comment]
@AnttHeik en tiedä, onko asettelut tismalleen samalla tavalla kuin aiemmin, mutta niiden pitäisi olla validit, kun liitännäisen tarkistus hyväksyy ne.

**Comment by pknuuti** [comment]
Mistä minä löydän Vaaran vanhan asetuksen? Ei mulla sitä missään ole ylhäällä :(

**Comment by AnneliO** [comment]
> Mistä minä löydän Vaaran vanhan asetuksen? Ei mulla sitä missään ole ylhäällä :(

Ne taitaa löytyä vanhasta järjestelmäasetuksesta, joka löytyy vielä Paikalliset tiedot -osiosta nimellä [MarcToFrameworkcodeAutoconvert](https://vaara.koha-suomi.fi/cgi-bin/koha/admin/systempreferences.pl?op=add_form&searchfield=MarcToFrameworkcodeAutoconvert) (ei löydy järjestelmäasetushaulla, mutta löytyy tuolta sivulta).

**Comment by pknuuti** [comment]
Kiitos Anneli!

**Comment by ajrajala** [comment]
Olikos tämä tarkoitus tuoda vielä muille kimpoille testattavaksi?

**Comment by AnneliO** [comment]
Sitä parempihan se on, mitä useampi testaa.

**Comment by pknuuti** [comment]
Marja testasi tätä Vaaran testillä ja sai seuraavanlaisen tuloksen:
"Vaara testissä kävin muuttamassa tietueelle kirjapohjan oletukseksi ja toin z-haulla Tätistä tiedot. Tallentaessa herjaa 942-kenttää eli se ei nyt sitten päivity pohjan mukaan."
Mikä tässä on ongelmana? MarcToFrameworkcodeAutoconvert-asetus testillä määritelty kuten ennenkin.

**Comment by AnttHeik** [comment]
> Marja testasi tätä Vaaran testillä ja sai seuraavanlaisen tuloksen: "Vaara testissä kävin muuttamassa tietueelle kirjapohjan oletukseksi ja toin z-haulla Tätistä tiedot. Tallentaessa herjaa 942-kenttää eli se ei nyt sitten päivity pohjan mukaan." Mikä tässä on ongelmana? MarcToFrameworkcodeAutoconvert-asetus testillä määritelty kuten ennenkin.

Hei, liittyen 942-kentän tiedon häviämiseen Kati mainitsee tiketissä https://github.com/KohaSuomi/Koha/issues/481#issuecomment-1782730588 näin Z39.50/SRU-hausta:

"Testi-erikoisuus: tietueen 942-kenttä poistui (942c-arvo), kun sääntönä tämä [...]
Testasin tuotannossa: testiä vastaava tuotannon 942-kentän ydistämissääntö toimii oikein ja säilyttää 942-kentän."

Voiko olla, että tämän takia tuo 942-kentän tieto häviää testillä?

Jos on, niin minusta tämän toiminnon voisi jo sitten kytkeä päälle kaikkiin paikalliskantoihin.

**Comment by AnneliO** [comment]
@paxed asennatko tämän kaikille testeille?

**Comment by Kati-Helle** [comment]
En nyt löydä Helle-testissä "Auto Framework Code" - pluginia täältä: Tools/Tool plugins

**Comment by Kati-Helle** [comment]
Helle-testillä on nyt "Auto Framework Code" - plugin. Lisäsin asetuksen määrityksiin tässä tiketissä mainitut OUTIn määritykset.

Helle-testissä testausta.

Olemassa olevan tietueen korvaus Z39.50/SRU-haulla
- Helle-tietueella (biblionumber=59) on tallennuspohjana Oletus
- korvaan tietueen Z39.50/SRU-haulla
- tietuekorvauksen jälkeen Helle-tietueen muokkauksessa tallennuspohja on muuttunut ja se on Kirja
- tallennan tietueen 
- tarkistan tallennetun tietueen tallennuspohjan menemällä tietueen muokkaukseen: tallennuspohjana on edelleen Kirja
- vaihdan tietueen muokkauksessa tallennuspohjaksi Oletus
- tallennuksen jälkeen tallennuspohja on muuttunut ja se on Kirja

Uuden tietueen tuonti z39.50/SRU-haulla
- Lisää Marc-tietue -kuvailutoiminnossa tallennuspohjana on Oletus
- haen tietueen Z39.50/SRU-haulla
- tuodun uuden tietueen (biblionumber=1631064) tallennuspohjana on Kirja
- tallennan tietueen
- menen tallennetun uuden tietueen muokkausnäytölle: tallennuspohjana on Kirja

**Comment by pknuuti** [comment]
Vaaran testillä testattu nyt uudelleen. Toimii kuvailupohjan säilyminen oikeana.

**Comment by pknuuti** [comment]
Testasin nyt vielä uudelleen, toimii Vaaran testillä.

**Comment by AnttHeik** [comment]
OUTIssa toimii muuten hyvin, mutta hoksasin tällaisen virheen:

Kun perustiedot-näytöllä korvaan oletuspohjalla olevan tietueen Z39.50/SRU-haulla ja valitsee tuotavaksi tietueen Melindasta, niin 942-kenttä tuplaantuu. Jos tietue on tallennettu alun perin kirja-pohjalla, niin kenttä ei tuplaannu ja aineistotyyppi säilyy 942c-kentässä. .Jos taas tuon tietueen TäTistä, niin 942-kenttä tyhjenee oli alkuperäinen tietue oletus- tai kirjapohjalla. 942-kenttä ei tuplaannu näissä tapauksissa. Esim. tietueella 2335959 voi testata.

**Comment by Kati-Helle** [comment]
Helle-testissä lisätestausta Melinda-yhdistelyyn liittyen (yhteys TäTiin ei jostain syystä toimi edelleenkään).

Helle-tietueella (biblionumber=30) kuvailupohjana Oletus: 
- korvaus Melinda-tietueella ja 942-kenttä ei tuplaannu
- aineistotyyppi (942c-kenttä) on säilynyt 
- kuvailupohjaksi on muuttunut Kirja

Helle-tietueella (biblionumber=32) kuvailupohjana Kirja:
- korvaus Melinda-tietueella ja 942-kenttä ei tuplaannu
- aineistotyyppi (942c-kenttä) on säilynyt 
- kuvailupohjana on edelleen Kirja

**Comment by AnneliO** [comment]
> Z39.50/SRU-haulla

Tämä todennäköisesti ei liity tallennuspohjiin vaan MARC-yhdistelysääntöihin, joten tuodaan toiminnallisuus tuotantoon.

**Comment by AnneliO** [comment]
> Tässä on OUTIn asetukset Auto Framwork Code -liitännäisen määrittelyyn:
> 
> ```
> ---
> - 000/06 + 000/07:
>    a+s: SER
> - 000/06:
>    a: KIR
>    c: NUO
>    e: MAP
>    g: VR
>    j: CDA
>    r: LAU
>    t: KIR
> - 008/26 + 000/06:
>    g+m: KP
> ```

Käykää pääkäyttäjät lisäämässä vielä Auto Framework Code -liitännäisen asetuksiin nämä määritykset.

HUOM! Tarkista ensin, että kuvailupohjien lyhenteet ovat oikein ja vastaavat oman kimpan kuvailupohjien lyhenteitä. Jos asetukseen määritettyä kuvailupohjan lyhennettä ei ole olemassa omassa kimpassa, näkyvät tietueet ja niteet "tyhjinä", kun niitä muokkaa.

**Comment by pknuuti** [comment]
Muistutan tämän tiketin olemassaolosta Matrixissa ja suljen tiketin.

**Comment by piiaseme** [comment]
OUTIn määrittely tällä hetkellä:
---
- 000/06 + 000/07:
   a+s: SER
- 000/06:
   a: KIR
   c: NUO
   e: MAP
   g: VR
   j: CDA
   t: KIR
- 008/26 + 000/06:
   g+m: KP
- 008/33 + 000/06:
   g+r: LAU

**Comment by LeenaKinnunen** [comment]
Lapissa määrittely nyt nextillä pluginissa: 
- 000/06 + 000/07:
   a+s: SER
- 000/06:
   a: KIR
   c: NUO
   e: MAP
   g: VR
   j: SR
   r: ESI
   t: KIR

Ei testattu tarkemmin.
